### ISSUE TITLE
Unhandled Exception: System.Exception: Exception during execution of external process: 71235

### ISSUE THREAD

**Issue by ningxiaolian** [blahoink/maxquant_linux_guide#10]
Hi, @atc3,
I am a student at the University of Chinese Academy of Science. I encountered a problem when I run Maxquant on the Linux system, the error was listed bellow. My data is Lumos and I can successfully run untill the step "Label-free normalization". Then I found out the error from the "Label-free_normalization 11.error.txt" file. It seems the normalization didn't work. Could you give me some help or suggestions?  I am looking forward to your reply!

[Label-free_normalization 11.error.txt](https://github.com/atc3/maxquant_linux_guide/files/8314755/Label-free_normalization.11.error.txt)
`Unhandled Exception: System.Exception: Exception during execution of external process: 71235
   at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
   at QueueingSystem.WorkDispatcher.Work(Object threadIndex)
   at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
/opt/gridengine/default/spool/cngb-compute-m13-35/job_scripts/5117348:`

**Comment by atc3** [comment]
Hi,

I unfortunately have not tested any of this on Lumos data. You may have better luck asking on the official MaxQuant Google group: https://groups.google.com/g/maxquant-list

**Comment by ningxiaolian** [comment]
Thank you so much for your reply!  I will consult the offical MaxQuant group!

**Comment by zhengjiebioinfo** [comment]
> Hi, @atc3, I am a student at the University of Chinese Academy of Science. I encountered a problem when I run Maxquant on the Linux system, the error was listed bellow. My data is Lumos and I can successfully run untill the step "Label-free normalization". Then I found out the error from the "Label-free_normalization 11.error.txt" file. It seems the normalization didn't work. Could you give me some help or suggestions? I am looking forward to your reply!
> 
> [Label-free_normalization 11.error.txt](https://github.com/atc3/maxquant_linux_guide/files/8314755/Label-free_normalization.11.error.txt) `Unhandled Exception: System.Exception: Exception during execution of external process: 71235 at QueueingSystem.WorkDispatcher.ProcessSingleRunExternalProcess(Int32 taskIndex, Int32 threadIndex) at QueueingSystem.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex) at QueueingSystem.WorkDispatcher.Work(Object threadIndex) at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() /opt/gridengine/default/spool/cngb-compute-m13-35/job_scripts/5117348:`

Hello, I have also encountered the same problem. If you have solved this, could you please give me some suggestions or solutions?
